/* Generated by the Nim Compiler v1.9.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function toJSStr(s_33556863) {
  var result_33556864 = null;

    var res_33556902 = newSeq_33556881((s_33556863).length);
    var i_33556903 = 0;
    var j_33556904 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556903 < (s_33556863).length)) break Label2;
          var c_33556905 = s_33556863[i_33556903];
          if ((c_33556905 < 128)) {
          res_33556902[j_33556904] = String.fromCharCode(c_33556905);
          i_33556903 += 1;
          }
          else {
            var helper_33556918 = newSeq_33556881(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556919 = c_33556905.toString(16);
                  if ((((code_33556919) == null ? 0 : (code_33556919).length) == 1)) {
                  helper_33556918.push("%0");;
                  }
                  else {
                  helper_33556918.push("%");;
                  }
                  
                  helper_33556918.push(code_33556919);;
                  i_33556903 += 1;
                  if ((((s_33556863).length <= i_33556903) || (s_33556863[i_33556903] < 128))) {
                  break Label3;
                  }
                  
                  c_33556905 = s_33556863[i_33556903];
                }
            };
++excHandler;
            try {
            res_33556902[j_33556904] = decodeURIComponent(helper_33556918.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556902[j_33556904] = helper_33556918.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556904 += 1;
        }
    };
    if (res_33556902.length < j_33556904) { for (var i = res_33556902.length ; i < j_33556904 ; ++i) res_33556902.push(null); }
               else { res_33556902.length = j_33556904; };
    result_33556864 = res_33556902.join("");

  return result_33556864;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_33556881(len_33556883) {
  var result_33556884 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 608;
    result_33556884 = new Array(len_33556883); for (var i = 0 ; i < len_33556883 ; ++i) { result_33556884[i] = null; }  framePtr = F.prev;

  return result_33556884;

}

function HEX3Aanonymous_654311427() {
  var F = {procname: "jscore_examples_3.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
  framePtr = F;
    F.line = 146;
    rawEcho([77,105,99,114,111,116,97,115,107]);
  framePtr = F.prev;

  
}
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
F.line = 146;
queueMicrotask(HEX3Aanonymous_654311427);
framePtr = F.prev;
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
